import { test, expect } from '@playwright/test';

// Test suite for Document Creation on Refrens
// Covers: Quotations, Invoices, Proforma Invoices, Payment Receipts, Sales Orders, etc.

test.describe('Document Creation - Invoice', () => {
  test.beforeEach(async ({ page }) => {
    // Navigate to the app and authenticate using stored auth state
    await page.goto('/app');
    await page.waitForLoadState('networkidle');
  });

  // Step 1: Navigate to Invoice Dashboard
  test('Step 1: Navigate to Invoice Dashboard and open Create New Invoice', async ({ page }) => {
    // Click on Sidebar > Sales
    await page.click('button[aria-label="Menu"]');
   
    await page.waitForLoadState('networkidle');
    // Click on Sales
    await page.click('button[aria-label="Sales"]');
    await page.waitForLoadState('networkidle');

    // Verify we're on Invoice Dashboard
    await expect(page).toHaveTitle(/Invoice/i);

    // Click on "Create New Invoice" button
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Verify we're redirected to invoice creation page
    await expect(page).toHaveURL(/.*invoice.*create/i);
    await expect(page.locator('text=Invoice Details')).toBeVisible();
  });

  // Step 2: Fill Out Invoice Details
  test('Step 2: Fill Out Invoice Details (Title, Number, Date, Due Date)', async ({ page }) => {
    // Navigate to create new invoice
    await page.click('button[aria-label="Menu"]');
    await page.waitForLoadState('networkidle');
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Fill Invoice Title
    const invoiceTitleField = page.locator('input[name*="title"], input[placeholder*="Invoice Title"]').first();
    await invoiceTitleField.fill('Tax Invoice');

    // Verify Invoice Number is auto-generated
    const invoiceNumberField = page.locator('input[name*="number"], input[placeholder*="Invoice Number"]');
    const autoGeneratedNumber = await invoiceNumberField.inputValue();
    expect(autoGeneratedNumber).toBeTruthy();

    // Set Invoice Date (default is today, but we can change it)
    const invoiceDateField = page.locator('input[type="date"][name*="date"], input[placeholder*="Invoice Date"]').first();
    await invoiceDateField.fill('2026-02-11');

    // Set Due Date
    const dueDateField = page.locator('input[type="date"][name*="due"], input[placeholder*="Due Date"]').nth(0);
    await dueDateField.fill('2026-02-26'); // 15 days from invoice date

    // Verify fields are filled
    await expect(invoiceTitleField).toHaveValue('Tax Invoice');
    await expect(invoiceDateField).toHaveValue('2026-02-11');
  });

  // Step 3: Add Business Logo
  test('Step 3: Add Business Logo', async ({ page }) => {
    // Navigate to create new invoice
    await page.click('button[aria-label="Menu"]');
    await page.waitForLoadState('networkidle');
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Click on "Add Business Logo"
    const addLogoBtn = page.locator('button:has-text("Add Business Logo"), button:has-text("Business Logo")');
    await addLogoBtn.click();
    await page.waitForLoadState('networkidle');

    // Check if file input or upload dialog appears
    const fileInput = page.locator('input[type="file"]');
    expect(fileInput).toBeDefined();

    // Verify logo upload section is visible
    const logoSection = page.locator('text=Add Business Logo, text=Business Logo');
    await expect(logoSection.first()).toBeVisible();
  });

  // Step 4: Add Client Information
  test('Step 4: Add Client Information (Select or Create New)', async ({ page }) => {
    // Navigate to create new invoice
    await page.click('button[aria-label="Menu"]');
    await page.waitForLoadState('networkidle');
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Look for client dropdown/field
    const clientField = page.locator('[placeholder*="Client"], [placeholder*="Select Client"], select:has-text("Client")').first();
    
    // Verify client field is visible
    await expect(clientField).toBeVisible();

    // Option 1: Select existing client
    await clientField.click();
    await page.waitForLoadState('networkidle');
    
    // Check if dropdown options appear
    const clientOptions = page.locator('[role="option"]').first();
    if (await clientOptions.isVisible()) {
      await clientOptions.click();
    } else {
      // Option 2: Add new client by clicking "Add New Client" link
      const addNewClientBtn = page.locator('button:has-text("Add New Client"), a:has-text("Add New Client")');
      if (await addNewClientBtn.isVisible()) {
        await addNewClientBtn.click();
        await page.waitForLoadState('networkidle');
        
        // Fill client details
        await page.fill('input[placeholder*="Client Name"]', 'Test Client');
        await page.fill('input[placeholder*="Email"]', 'client@example.com');
        await page.fill('input[placeholder*="Phone"]', '1234567890');
      }
    }
  });

  // Step 5: Add Shipping Details
  test('Step 5: Add Shipping Details (if different from billing)', async ({ page }) => {
    // Navigate to create new invoice
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Add client first
    const clientField = page.locator('[placeholder*="Client"], [placeholder*="Select Client"]').first();
    await clientField.click();
    await page.locator('[role="option"]').first().click({ timeout: 5000 }).catch(() => {});

    // Look for "Add Shipping Details" checkbox or toggle
    const shippingCheckbox = page.locator('input[type="checkbox"][name*="shipping"], label:has-text("Add Shipping Details")');
    
    if (await shippingCheckbox.isVisible()) {
      await shippingCheckbox.click();
      await page.waitForLoadState('networkidle');

      // Fill shipping address details
      const shippingFields = page.locator('[placeholder*="Shipping"], [placeholder*="Address"]');
      const fieldCount = await shippingFields.count();
      if (fieldCount > 0) {
        await shippingFields.nth(0).fill('123 Shipping Street');
        await shippingFields.nth(1).fill('Shipping City');
        if (fieldCount > 2) {
          await shippingFields.nth(2).fill('12345');
        }
      }
    }
  });

  // Step 6: Configure Taxes, Currency, Number, and Column/Formulas
  test('Step 6: Configure Tax, Currency, and Number Format', async ({ page }) => {
    // Navigate to create new invoice
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // 6.1: Configure Tax
    const configureTaxBtn = page.locator('button:has-text("Configure Tax"), button:has-text("Tax")').first();
    if (await configureTaxBtn.isVisible()) {
      await configureTaxBtn.click();
      await page.waitForLoadState('networkidle');
      
      // Add tax rate (e.g., GST 18%)
      const taxInput = page.locator('input[placeholder*="Tax"], input[placeholder*="GST"]').first();
      if (await taxInput.isVisible()) {
        await taxInput.fill('18');
      }
    }

    // 6.2: Select Currency
    const currencySelect = page.locator('select:has-text("Currency"), [placeholder*="Currency"]').first();
    if (await currencySelect.isVisible()) {
      await currencySelect.selectOption('USD'); // or another currency
    }

    // 6.3: Configure Number Format
    const numberFormatBtn = page.locator('button:has-text("Number Format"), button:has-text("Format")').first();
    if (await numberFormatBtn.isVisible()) {
      await numberFormatBtn.click();
      await page.waitForLoadState('networkidle');
    }
  });

  // Step 7: Add Products/Services
  test('Step 7: Add Products/Services to Invoice', async ({ page }) => {
    // Navigate to create new invoice
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Find the products/items section
    const addItemBtn = page.locator('button:has-text("Add Item"), button:has-text("Add Product"), button:has-text("Add Service"), button:has-text("Add Line Item")').first();
    
    if (await addItemBtn.isVisible()) {
      await addItemBtn.click();
      await page.waitForLoadState('networkidle');

      // Fill product details
      const productNameField = page.locator('input[placeholder*="Product"], input[placeholder*="Item"], input[placeholder*="Service"]').first();
      await productNameField.fill('Web Development Service');

      const quantityField = page.locator('input[placeholder*="Quantity"], input[placeholder*="Qty"]').first();
      await quantityField.fill('1');

      const rateField = page.locator('input[placeholder*="Rate"], input[placeholder*="Price"]').first();
      await rateField.fill('5000');

      // Verify the item is added
      await expect(page.locator('text=Web Development Service')).toBeVisible();
    }
  });

  // Step 8: Additional Discounts/Charges
  test('Step 8: Add Additional Discounts/Charges', async ({ page }) => {
    // Navigate to create new invoice
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Add a product first
    const addItemBtn = page.locator('button:has-text("Add Item"), button:has-text("Add Product")').first();
    if (await addItemBtn.isVisible()) {
      await addItemBtn.click();
      await page.waitForLoadState('networkidle');
      await page.locator('input[placeholder*="Product"]').first().fill('Test Product');
      await page.locator('input[placeholder*="Quantity"]').first().fill('1');
      await page.locator('input[placeholder*="Rate"]').first().fill('1000');
    }

    // Look for "Additional Discounts/Charges" button
    const discountBtn = page.locator('button:has-text("Discount"), button:has-text("Charges"), button:has-text("Additional")').first();
    
    if (await discountBtn.isVisible()) {
      await discountBtn.click();
      await page.waitForLoadState('networkidle');

      // Add discount
      const discountField = page.locator('input[placeholder*="Discount"]').first();
      if (await discountField.isVisible()) {
        await discountField.fill('10'); // 10% discount
      }

      // Add additional charges if needed
      const chargesField = page.locator('input[placeholder*="Charges"], input[placeholder*="Shipping"]').first();
      if (await chargesField.isVisible()) {
        await chargesField.fill('100'); // $100 shipping charge
      }
    }
  });

  // Step 9: Signature and Footer Details
  test('Step 9: Add Signature to Document', async ({ page }) => {
    // Navigate to create new invoice
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Look for signature section
    const signatureSection = page.locator('button:has-text("Signature"), button:has-text("Sign"), text=Signature').first();
    
    if (await signatureSection.isVisible()) {
      await signatureSection.click();
      await page.waitForLoadState('networkidle');

      // Check if signature pad or upload option is available
      const uploadSignatureBtn = page.locator('button:has-text("Upload"), input[type="file"]').first();
      if (await uploadSignatureBtn.isVisible()) {
        // Could upload an image
        expect(uploadSignatureBtn).toBeDefined();
      }
    }
  });

  // Step 10: Add Terms & Conditions
  test('Step 10: Add Terms & Conditions', async ({ page }) => {
    // Navigate to create new invoice
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Look for Terms & Conditions section
    const termsBtn = page.locator('button:has-text("Terms"), button:has-text("Terms & Conditions"), text=Terms').first();
    
    if (await termsBtn.isVisible()) {
      await termsBtn.click();
      await page.waitForLoadState('networkidle');

      // Option 1: Add terms manually
      const termsTextarea = page.locator('textarea[placeholder*="Terms"]').first();
      if (await termsTextarea.isVisible()) {
        await termsTextarea.fill('Payment is due within 30 days of invoice date.');
      }

      // Option 2: Select from previous T&Cs
      const selectPreviousBtn = page.locator('button:has-text("Select"), button:has-text("Previous")').first();
      if (await selectPreviousBtn.isVisible()) {
        await selectPreviousBtn.click();
        await page.waitForLoadState('networkidle');
      }
    }
  });

  // Step 11: Add Notes, Attachments, and Contact Details
  test('Step 11: Add Notes, Attachments, and Contact Details', async ({ page }) => {
    // Navigate to create new invoice
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // 11.1: Add Notes
    const notesField = page.locator('textarea[placeholder*="Notes"], textarea[placeholder*="Note"]').first();
    if (await notesField.isVisible()) {
      await notesField.fill('Thank you for your business!');
    }

    // 11.2: Add Attachments
    const attachmentBtn = page.locator('button:has-text("Attachment"), button:has-text("Attach")').first();
    if (await attachmentBtn.isVisible()) {
      await attachmentBtn.click();
      const fileInput = page.locator('input[type="file"]');
      expect(fileInput).toBeDefined();
    }

    // 11.3: Add Contact Details
    const contactField = page.locator('input[placeholder*="Contact"], input[placeholder*="Phone"], input[placeholder*="Email"]').first();
    if (await contactField.isVisible()) {
      // Contact fields might already be populated with business info
      expect(contactField).toBeDefined();
    }

    // 11.4: Add Additional Info
    const additionalInfoBtn = page.locator('button:has-text("Additional"), button:has-text("More Info")').first();
    if (await additionalInfoBtn.isVisible()) {
      await additionalInfoBtn.click();
    }
  });

  // Step 12: Recurring Document
  test('Step 12: Enable Recurring Document (if applicable)', async ({ page }) => {
    // Navigate to create new invoice
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Look for recurring toggle
    const recurringToggle = page.locator('input[type="checkbox"][name*="recurring"], label:has-text("Recurring")').first();
    
    if (await recurringToggle.isVisible()) {
      // Check if it's already enabled
      const isChecked = await recurringToggle.isChecked();
      
      if (!isChecked) {
        await recurringToggle.click();
        await page.waitForLoadState('networkidle');

        // Set recurrence period
        const recurrenceSelect = page.locator('select[name*="recurrence"], select[name*="period"]').first();
        if (await recurrenceSelect.isVisible()) {
          await recurrenceSelect.selectOption('monthly'); // or weekly, daily, etc.
        }
      }
    }
  });

  // Step 13: Review and Save
  test('Step 13: Review Invoice Details and Save', async ({ page }) => {
    // Navigate to create new invoice
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Fill minimum required details
    const clientField = page.locator('[placeholder*="Client"]').first();
    if (await clientField.isVisible()) {
      await clientField.click();
      await page.locator('[role="option"]').first().click({ timeout: 5000 }).catch(() => {});
    }

    // Add at least one item
    const addItemBtn = page.locator('button:has-text("Add Item"), button:has-text("Add Product")').first();
    if (await addItemBtn.isVisible()) {
      await addItemBtn.click();
      await page.waitForLoadState('networkidle');
      await page.locator('input[placeholder*="Product"]').first().fill('Test Item');
      await page.locator('input[placeholder*="Quantity"]').first().fill('1');
      await page.locator('input[placeholder*="Rate"]').first().fill('1000');
    }

    // Click "Save and Continue" button
    const saveBtn = page.locator('button:has-text("Save and Continue"), button:has-text("Save"), button:has-text("Next")').first();
    if (await saveBtn.isVisible()) {
      await saveBtn.click();
      await page.waitForLoadState('networkidle');

      // Verify we moved to next step or document is saved
      await expect(page).toHaveURL(/.*invoice|.*success/i);
    }
  });

  // Step 14: Add Banking Details
  test('Step 14: Add Banking Details (Bank, UPI, Payment Links)', async ({ page }) => {
    // Navigate to existing invoice or create new one
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Look for banking/payment details section
    const bankingBtn = page.locator('button:has-text("Bank"), button:has-text("Payment"), button:has-text("Payment Details")').first();
    
    if (await bankingBtn.isVisible()) {
      await bankingBtn.click();
      await page.waitForLoadState('networkidle');

      // Add bank details
      const bankNameField = page.locator('input[placeholder*="Bank Name"]').first();
      if (await bankNameField.isVisible()) {
        await bankNameField.fill('Test Bank');
      }

      const accountNumberField = page.locator('input[placeholder*="Account"], input[placeholder*="Account Number"]').first();
      if (await accountNumberField.isVisible()) {
        await accountNumberField.fill('1234567890');
      }

      // Add UPI details if available
      const upiField = page.locator('input[placeholder*="UPI"]').first();
      if (await upiField.isVisible()) {
        await upiField.fill('testaccount@bank');
      }
    }
  });

  // Step 15: Customize Documents
  test('Step 15: Customize Document Template (Colors, Fonts, etc.)', async ({ page }) => {
    // Navigate to existing invoice or create new one
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Look for customize/template section
    const customizeBtn = page.locator('button:has-text("Customize"), button:has-text("Template"), button:has-text("Design")').first();
    
    if (await customizeBtn.isVisible()) {
      await customizeBtn.click();
      await page.waitForLoadState('networkidle');

      // Check for color customization
      const colorPicker = page.locator('input[type="color"]').first();
      if (await colorPicker.isVisible()) {
        await colorPicker.fill('#FF0000'); // Change to red
      }

      // Check for font selection
      const fontSelect = page.locator('select[name*="font"]').first();
      if (await fontSelect.isVisible()) {
        const options = await fontSelect.locator('option').count();
        if (options > 1) {
          await fontSelect.selectOption('1'); // Select different font
        }
      }
    }
  });

  // Complete End-to-End Test: Create a Full Invoice
  test('End-to-End: Create Complete Invoice with all details', async ({ page }) => {
    // Step 1: Navigate to Invoice Creation
    await page.click('text=Sales');
    await page.click('text=Invoices');
    await page.click('button:has-text("Create New Invoice")');
    await page.waitForLoadState('networkidle');

    // Step 2: Fill Invoice Details
    const invoiceTitleField = page.locator('input[placeholder*="Title"]').first();
    if (await invoiceTitleField.isVisible()) {
      await invoiceTitleField.fill('Standard Invoice');
    }

    // Step 3: Add Client
    const clientField = page.locator('[placeholder*="Client"]').first();
    if (await clientField.isVisible()) {
      await clientField.click();
      await page.locator('[role="option"]').first().click({ timeout: 5000 }).catch(() => {});
    }

    // Step 4: Add Product/Service
    const addItemBtn = page.locator('button:has-text("Add Item"), button:has-text("Add Product")').first();
    if (await addItemBtn.isVisible()) {
      await addItemBtn.click();
      await page.waitForLoadState('networkidle');
      await page.locator('input[placeholder*="Product"]').first().fill('Consulting Services');
      await page.locator('input[placeholder*="Quantity"]').first().fill('2');
      await page.locator('input[placeholder*="Rate"]').first().fill('2500');
    }

    // Step 5: Add Notes
    const notesField = page.locator('textarea[placeholder*="Notes"]').first();
    if (await notesField.isVisible()) {
      await notesField.fill('Invoice for services rendered in February 2026');
    }

    // Step 6: Save Invoice
    const saveBtn = page.locator('button:has-text("Save and Continue"), button:has-text("Save"), button:has-text("Submit")').first();
    if (await saveBtn.isVisible()) {
      await saveBtn.click();
      await page.waitForLoadState('networkidle');

      // Verify success
      const successMessage = page.locator('text=saved, text=Success, text=created').first();
      await expect(successMessage).toBeVisible({ timeout: 10000 }).catch(() => {
        // Alternative: Check if we're on invoice view page
        expect(page.url()).toContain('invoice');
      });
    }
  });
});

// Test suite for Other Document Types
test.describe('Document Creation - Other Document Types', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/app');
    await page.waitForLoadState('networkidle');
  });

  test('Create Quotation/Estimate', async ({ page }) => {
    await page.click('text=Sales');
    await page.locator('text=Quotations, text=Estimates').first().click();
    await page.locator('button:has-text("Create"), button:has-text("New")').first().click();
    await page.waitForLoadState('networkidle');
    
    // Verify quotation creation page loads
    await expect(page).toHaveURL(/.*quotation|.*estimate/i);
  });

  test('Create Proforma Invoice', async ({ page }) => {
    await page.click('text=Sales');
    await page.click('text=Proforma');
    await page.locator('button:has-text("Create"), button:has-text("New")').first().click();
    await page.waitForLoadState('networkidle');
    
    await expect(page).toHaveURL(/.*proforma/i);
  });

  test('Create Purchase Order', async ({ page }) => {
    await page.locator('text=Purchases, text=Buying').first().click();
    await page.locator('text=Purchase Order, text=PO').first().click();
    await page.locator('button:has-text("Create"), button:has-text("New")').first().click();
    await page.waitForLoadState('networkidle');
    
    await expect(page).toHaveURL(/.*purchase|.*po/i);
  });

  test('Create Delivery Note/Challan', async ({ page }) => {
    await page.locator('text=Sales, text=Inventory').first().click();
    await page.locator('text=Delivery, text=Challan').first().click();
    await page.locator('button:has-text("Create"), button:has-text("New")').first().click();
    await page.waitForLoadState('networkidle');
    
    await expect(page).toHaveURL(/.*delivery|.*challan/i);
  });
});
